version: "2"

run:
  tests: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  show-stats: true

issues:
  uniq-by-line: true

linters:
  enable:
    - asciicheck
    - cyclop
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - goconst
    - godot
    - misspell
    - nestif
    - revive

  settings:
    cyclop:
      max-complexity: 10
      package-average: 0.0

    dogsled:
      max-blank-identifiers: 2

    # TODO: Enable dupl linter when the project is more mature, during development it's raising false positives
    # dupl:
    #   threshold: 100

    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - fmt:.*
        - io/ioutil:^Read.*

    exhaustive:
      default-signifies-exhaustive: false

    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements.

    funlen:
      lines: 80
      statements: 40

    goconst:
      min-len: 3
      min-occurrences: 3

    godot:
      check-all: false

    misspell:
      locale: US

    nestif:
      min-complexity: 4

    revive:
      severity: warning
      rules:
        - name: atomic
        - name: line-length-limit
          arguments: [150]
        - name: argument-limit
          arguments: [5]
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes: 
        - github.com/org/project
