version: '3'

services:
  tsdb:
    image: timescale/timescaledb:2.6.0-pg14
    environment:
      POSTGRES_DB: plantd_development
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: plantd
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - tsdb_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/var/lib/redis

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3333:3000"
    environment:
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      # GF_SECURITY_ADMIN_USER: admin
      # GF_SECURITY_ADMIN_PASSWORD: plantd
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://loki:3100
            basicAuth: false
            isDefault: true
            version: 1
            editable: false
          - name: Postgres
            type: postgres
            url: tsdb:5432
            user: admin
            secureJsonData:
              password: 'plantd'
            jsonData:
              database: plantd_development
              sslmode: 'disable' # disable/require/verify-ca/verify-full
              maxOpenConns: 100 # Grafana v5.4+
              maxIdleConns: 100 # Grafana v5.4+
              maxIdleConnsAuto: true # Grafana v9.5.1+
              connMaxLifetime: 14400 # Grafana v5.4+
              postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
              timescaledb: true
        EOF
        /run.sh
    restart: unless-stopped
    volumes:
      # - ./.docker/grafana:/etc/grafana
      - grafana_data:/var/lib/grafana
    networks:
      - loki

networks:
  loki:

volumes:
  grafana_data:
  redis_data:
  tsdb_data:
