version: '3'

services:
  broker:
    image: registry.gitlab.com/plantd/broker:staging
    environment:
      PLANTD_BROKER_LOG_LEVEL: debug
      PLANTD_BROKER_LOG_FORMAT: json
      PLANTD_BROKER_ENDPOINT: 'tcp://*:9797'
    ports:
      - '9797:9797'
      - '11000:11000'
      - '11001:11001'
      - '12000:12000'
      - '12001:12001'
      - '13000:13000'
      - '13001:13001'
    restart: unless-stopped

  echo:
    image: org.plantd.module.echo:latest
    environment:
      PLANTD_BROKER_ENDPOINT: 'tcp://broker:9797'
      PLANTD_MODULE_ECHO_LOG_LEVEL: debug
      PLANTD_MODULE_ECHO_PORT: 5001
      PLANTD_MODULE_ECHO_ADDRESS: '0.0.0.0'
    ports:
      - '5001:5001'
    restart: unless-stopped
