root = "."
tmp_dir = "tmp"

[build]
cmd = "make build-logger"
bin = "build/plantd-logger"
full_bin = "build/plantd-logger"
include_ext = ["go"]
exclude_dir = [
  "broker",
  "build",
  "client",
  "coverage",
  "docs",
  "identity",
  "init",
  "module",
  "notebooks",
  "proxy",
  "scripts",
  "state",
  "templates",
  "tmp",
]
exclude_regex = ["_test.go"]
exclude_unchanged = true
delay = 1000 # ms
stop_on_error = true
log = "air.log"
send_interrupt = true

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
