name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['broker', 'core', 'identity', 'logger', 'proxy', 'state']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -qq -y \
            libczmq-dev \
            libsodium-dev \
            libzmq3-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: ${{ matrix.package }}
          version: v2.1.6
