name: test and coverage
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -qq -y \
            libczmq-dev \
            libsodium-dev \
            libzmq3-dev \
            make

      - name: Build
        run: make

      - name: Test
        run: make test
        env:
          COVERAGE: 1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/core.txt,./coverage/app.txt,./coverage/broker.txt,./coverage/identity.txt,./coverage/state.txt
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
